language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y build-essential libopencv-dev

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG # -DTESTS_ON=true

script: make all # test

