%YAML:1.0

# openFABMAPexe Settings File

#---------------------------------------------------------------------------

FilePaths:
   #The training data video should be of disjoint, non-overlapping scenes
   #and should not visit the same location more than once

   TrainPath: "C:\\pioneer\\fabmaptest\\MTODtrain.avi"

   #The test video should not overlap with the training video but should
   #have similar environment types.

   TestPath: "C:\\pioneer\\fabmaptest\\MTOD_1x5.avi"

   #All feature descriptors extracted from the training data. Used to
   #create the vocabulary/codebook

   TrainFeatDesc: "C:\\pioneer\\fabmaptest\\fm2test\\MTOD_train_book.yml"

   #All bag-of-words type whole image descriptors extracted from the 
   #training data. Used to create the chow-liu tree and used in the
   #FabMap 'new place' likelihood calculation

   TrainImagDesc: "C:\\pioneer\\fabmaptest\\fm2test\\MTOD_train_fabmap.yml"
   
   #The vocabulary/codebook data

   Vocabulary: "C:\\pioneer\\fabmaptest\\fm2test\\MTOD_vocab.yml"
   
   #The Chow-Liu Tree data

   ChowLiuTree: "C:\\pioneer\\fabmaptest\\fm2test\\MTOD_tree.yml"

   #The FabMap results

   FabMapResults: "C:\\pioneer\\fabmaptest\\fm2test\\MTOD_results_NewMaxOnly.txt"

#---------------------------------------------------------------------------

# openFABMAP running mode:

# "ShowFeatures"
# "GenerateVocabTrainData"
# "TrainVocabulary"
# "GenerateFABMAPTrainData"
# "TrainChowLiuTree"
# "RunOpenFABMAP"

Function: "RunOpenFABMAP"

#---------------------------------------------------------------------------

FeatureOptions:

   # Feature Detection Options
   # "FAST"
   # "STAR"
   # "SIFT"
   # "SURF"
   # "MSER"

   DetectorType: SURF

   FastDetector:
      Threshold: 50
      NonMaxSuppression: 1

   StarDetector:
      MaxSize: 32#45
      Response: 10 #30
      LineThreshold: 18 #10
      LineBinarized: 18 #8
      Suppression: 20 #5

   SiftDetector:
      Threshold: 0.04 #0.04
      EdgeThreshold: 10

   SurfDetector:
      HessianThreshold: 3000 #400
      NumOctaves: 4
      NumOctaveLayers: 2 
      Upright: 1

   MSERDetector:
      Delta: 5
      MinArea: 60
      MaxArea: 14400 
      MaxVariation: 0.25
      MinDiversity: 0.2
      MaxEvolution: 200  
      AreaThreshold: 1.01  
      MinMargin: 0.003  
      EdgeBlurSize: 5   

   # Descriptor Extraction Options
   # "SIFT"
   # "SURF"

   ExtractorType: "SURF"

#---------------------------------------------------------------------------

VocabTrainOptions:

   # a smaller clustersize increases the specificity of each codeword
   # and will increase the number of words in the vocabulary

   ClusterSize: 0.4

#---------------------------------------------------------------------------

ChowLiuOptions:

   # a large amount of data is required to store all mutual information from
   # which the minimum spanning tree is created. e.g. an 8000 word codebook 
   # requires 1.2 Gb RAM. Increasing the threshold results in information being 
   # discarded, and a lower memory requirement. Too high a threshold may result 
   # in necessary information being discarded and the tree not being created.
   #A threshold of 0 takes longer and may fail due to memory requirements

   LowerInfoBound: 0.0005

#---------------------------------------------------------------------------

# Method to add new location to the FabMap location list
# "All"
# "NewMaximumOnly"

FabMapPlaceAddition: "NewMaximumOnly"

openFabMapOptions:

   #Detector Model

   PzGe: 0.39
   PzGne: 0

   #The method to calculate the likelihood of a 'new location'
   # "Sampled"
   # "Meanfield"

   NewPlaceMethod: "Sampled"

   #if using "sampled" method how many samples from training data to use

   NumSamples: 1000

   # The option to switch off FabMap's feature dependency model (Chow-Liu tree)
   # in the likelihood calculations
   # "Naive"
   # "ChowLiu"

   BayesMethod: "ChowLiu"

   # The option to switch on and off the addition of a simple motion model
   # which assumes links between sequential additions to the query space.
   # 0 for False, 1 for True

   SimpleMotion: 0

   # Which version of openFABMAP to run
   # "FabMap1"
   # "FabMapLUT"
   # "FabMapFBO"
   # "FabMap2"

   FabMapVersion: "FabMap2"
      
   #FabMap1:

      # no additional options
      
   FabMapLUT:

      # precision with which to store precomputed values (decimal places)

      Precision = 6

   FabMapFBO:
      # The loglikelihood bound beneath the best hypothesis at which other
      # hypotheses are always retained

      RejectionThreshold: 1e-6
      
      # The likelihood bound of a hypothesis 'overtaking' the current best 
      # hypothesis, below which hypotheses are discarded. Used to compute delta

      PsGd: 1e-6

      # The largest value of delta when computing it via the bisection method

      BisectionStart: 512

      # The number of iterations to perform the bisection. Bisection accuracy = 
      # BisectionStart / 2^BisectionIts

      BisectionIts: 9
      

   #FabMap2:

      # no additional options

#---------------------------------------------------------------------------
